const app=document.querySelector('#app');
const money=value=>typeof value==='number'?new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(value):'Not determinable';
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const label=value=>String(value||'').replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase()).replace(/_/g,' ');
const text=value=>Array.isArray(value)?value.join(', '):typeof value==='object'&&value!==null?JSON.stringify(value):String(value??'—');

try{
  const response=await fetch('/submission.json');
  if(!response.ok)throw new Error(`Submission file returned ${response.status}`);
  const data=await response.json();
  const material=data.decisions.filter(d=>d.reviewTier==='material_judgment');
  const p=data.statements.profitAndLoss||{},cf=data.statements.cashFlow||{},bs=data.statements.balanceSheet||{};
  const rows=object=>Object.entries(object||{}).filter(([,v])=>typeof v!=='object'||v===null).map(([k,v])=>`<div class="row"><span>${esc(label(k))}</span><b>${esc(typeof v==='number'?money(v):text(v))}</b></div>`).join('');
  const nested=object=>Object.entries(object||{}).map(([k,v])=>typeof v==='object'&&v!==null?`<h3>${esc(label(k))}</h3>${rows(v)}`:`<div class="row"><span>${esc(label(k))}</span><b>${esc(typeof v==='number'?money(v):text(v))}</b></div>`).join('');
  const uncertainties=(data.uncertainties||[]).map(u=>`<article class="schedule"><h3>${esc(u.issue)}</h3><p>${esc(u.effect)}</p><p><span class="tag ${u.priority==='critical'?'open':''}">${esc(u.priority)} priority</span></p></article>`).join('');
  const checks=(data.reconciliations||[]).map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.calculation||'—')}</td><td><span class="tag ${String(r.status).includes('cannot')||String(r.status).includes('does not')?'open':''}">${esc(r.status)}</span></td></tr>`).join('');
  const schedules=Object.entries(data.schedules||{}).map(([name,body])=>`<article class="schedule"><h3>${esc(label(name))}</h3>${typeof body==='object'?nested(body):`<p>${esc(body)}</p>`}</article>`).join('');
  const evidence=(data.evidence||[]).map(e=>`<article class="evidence"><b>${esc(e.id)}</b><span>${esc(e.source)}</span><br><span>Reliability: ${esc(e.reliability)}</span></article>`).join('');
  const uncertaintyCount=(data.uncertainties||[]).length;
  const criticalCount=(data.uncertainties||[]).filter(x=>x.priority==='critical').length;

  app.innerHTML=`<div class="shell">
    <section class="hero" id="overview"><div><p class="eyebrow">Evidence-led reconstruction · 31 August 2026</p><h1>Divorce Party<br>International Ltd.</h1><p class="hero-copy">Complete, reconciled financial reconstruction for board review. Closing inventory uses the €121,000 physical-count basis; the conflicting €405,000 consumption figure is disclosed but not mixed into the statements. Insurance is separately identified as an instructor-supplied correction.</p></div><div class="case-meta"><strong>Case ${esc(data.caseId)}</strong>Personally certified by ${esc(data.student?.name)} · ${esc(data.student?.id)}<br>Submission schema ${esc(data.schemaVersion)}</div></section>
    <section class="metric-grid"><article class="metric"><span class="metric-label">Reconstructed net profit</span><strong>${money(p.netProfit)}</strong><small>Complete P&amp;L</small></article><article class="metric"><span class="metric-label">Closing cash</span><strong>${money(cf.closingCash)}</strong><small>Reconciled to bank confirmation</small></article><article class="metric"><span class="metric-label">Total assets</span><strong>${money(bs.assets?.totalAssets)}</strong><small>Balances to liabilities and equity</small></article><article class="metric"><span class="metric-label">Disclosed uncertainties</span><strong>${uncertaintyCount}</strong><small>items retained for follow-up</small></article></section>
    <div class="tabbar" role="tablist"><button class="active" data-tab="executive">Decision brief</button><button data-tab="evidence">Evidence log</button><button data-tab="statements">Account snapshot</button><button data-tab="schedules">Working papers</button><button data-tab="decisions">Decision register</button><button data-tab="ai">Judgment audit</button></div>
    <section class="panel active" id="executive"><div class="lead">${esc(data.boardRecommendation?.decision)}</div><div class="two-col"><article class="card recommendation"><p class="eyebrow">Board recommendation</p><h2>Immediate actions</h2><ul>${(data.boardRecommendation?.immediateActions||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h3>Core operations</h3><p>${esc(data.boardRecommendation?.coreOperations)}</p></article><article class="card"><p class="eyebrow">Material uncertainties</p><h2>Items requiring resolution</h2>${uncertainties}</article></div><h2 class="section-title" style="margin-top:34px">Required financial checks</h2><table class="check-table"><thead><tr><th>Reconciliation</th><th>Calculation</th><th>Status</th></tr></thead><tbody>${checks}</tbody></table></section>
    <section class="panel" id="statements"><h2 class="section-title">Financial statements</h2><p class="section-note">Amounts and reconciliations are shown exactly as certified in the submitted JSON.</p><div class="statement-grid"><article class="statement-card"><span class="status confirmed">Reconciled</span><h3>Profit &amp; loss</h3>${rows(p)}</article><article class="statement-card"><span class="status confirmed">Reconciled</span><h3>Cash flow</h3>${rows(cf)}</article><article class="statement-card"><span class="status confirmed">Reconciled</span><h3>Balance sheet</h3>${nested(bs)}</article></div></section>
    <section class="panel" id="schedules"><h2 class="section-title">Supporting schedules</h2><p class="section-note">Detailed source-based calculations behind the reconstruction.</p>${schedules}</section>
    <section class="panel" id="evidence"><h2 class="section-title">Evidence register</h2><p class="section-note">The certified conclusions cite the case files below.</p><div class="evidence-grid">${evidence}</div></section>
    <section class="panel" id="decisions"><h2 class="section-title">All 100 decisions</h2><p class="section-note">Search a decision, then select it to view its certified answer, evidence and confidence.</p><div class="tools"><input id="decision-search" type="search" placeholder="Search ID, question or answer"><select id="tier-filter"><option value="all">All decisions</option><option value="operational">Operational</option><option value="material_judgment">Material judgments</option></select></div><div id="decision-list" class="decision-list"></div></section>
    <section class="panel" id="ai-trail"><h2 class="section-title">AI review trail · ${material.length} material judgments</h2><p class="section-note">Each material judgment preserves the first proposal, independent challenge, student reasoning and correction effect versus the existing management record. Original cash transactions are reported once in the cash-flow statement.</p><div class="trail">${material.map(trail).join('')}</div></section>
  </div>`;

  function impact(effect={}){return ['profit','cash','assets','liabilities','equity'].map(k=>`<span>${k}: ${effect[k]===null||effect[k]===undefined?'not quantified':money(effect[k])}</span>`).join('')}
  function trail(d){return `<article class="trail-card"><h3>${esc(d.id)} · ${esc(d.question)}</h3><span class="tag">${esc(d.confidence)} confidence</span>${d.changedFromAI?'<span class="flag risk">student override</span>':''}<h4>Certified answer</h4><p>${esc(d.answer)}</p><h4>First AI proposal</h4><p>${esc(d.aiProposal)}</p><h4>Independent challenge</h4><p>${esc(d.independentChallenge)}</p><h4>Student reasoning</h4><p>${esc(d.studentReasoning)}</p><h4>Correction effect vs management record</h4><div class="impact">${impact(d.statementEffect)}</div></article>`}
  function decision(d){const kind=d.reviewTier==='material_judgment'?'material':'';return `<article class="decision" data-decision="${esc(d.id)}"><span class="decision-id">${esc(d.id)}</span><div><div class="decision-question">${esc(d.question)}</div><div class="decision-meta">${esc(d.category)} · ${esc(d.confidence)} confidence</div></div><span class="tier ${kind}">${d.reviewTier==='material_judgment'?'material':'operational'}</span></article><div id="detail-${esc(d.id)}" class="detail"><h3>${esc(d.id)} · Certified decision</h3><p>${esc(d.answer)}</p><h4>Evidence</h4><ul>${d.evidence.map(e=>`<li>${esc(e)}</li>`).join('')}</ul>${d.reviewTier==='material_judgment'?`<h4>AI review</h4><p><b>First AI:</b> ${esc(d.aiProposal)}\n\n<b>Independent challenge:</b> ${esc(d.independentChallenge)}\n\n<b>Student reasoning:</b> ${esc(d.studentReasoning)}</p>`:''}</div>`}
  const list=document.querySelector('#decision-list');
  function renderDecisions(){const query=document.querySelector('#decision-search').value.toLowerCase(),tier=document.querySelector('#tier-filter').value;const shown=data.decisions.filter(d=>(tier==='all'||d.reviewTier===tier)&&`${d.id} ${d.question} ${d.answer}`.toLowerCase().includes(query));list.innerHTML=shown.map(decision).join('')||'<article class="schedule"><p>No decisions match this search.</p></article>';list.querySelectorAll('.decision').forEach(node=>node.onclick=()=>document.querySelector(`#detail-${node.dataset.decision}`).classList.toggle('show'));}
  renderDecisions();document.querySelector('#decision-search').oninput=renderDecisions;document.querySelector('#tier-filter').onchange=renderDecisions;
  if(location.pathname==='/review'){
    document.body.classList.add('assessor');
    const low=data.decisions.filter(d=>d.confidence==='low').length;
    const overrides=material.filter(d=>d.changedFromAI).length;
    document.querySelector('#executive').insertAdjacentHTML('afterbegin',`<div class="review-flags"><div><b>${overrides}</b> student overrides</div><div><b>${low}</b> low-confidence decisions</div><div><b>${criticalCount}</b> critical uncertainties</div><div><b>${material.length}</b> material calls reviewed</div></div>`);
    document.querySelector('#ai-trail').classList.add('active');
  }
  document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));button.classList.add('active');document.querySelector(`#${button.dataset.tab==='ai'?'ai-trail':button.dataset.tab}`).classList.add('active');});
}catch(error){app.innerHTML=`<div class="error"><h1>Submission could not be loaded</h1><p>${esc(error.message)}</p><p>Ensure <code>/submission.json</code> is deployed with the site.</p></div>`;}
